# DEM0 TÉCNICA DE LA RED LSTM (Keras/TensorFlow)
## Demo básica sin predicción 



In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM

# Preparación de los datos - 3 pasos de tiempo, 1 característica
datos = np.array([0.5, 0.4, 0.3]).reshape((1, 3, 1))

# Creamos la arquitectura base
entrada = Input(shape=(3,1))  # Define que miramos 3 pasos al pasado con 1 dato cada vez (temperatura de las 3 últimas horas)  
lstm_out = LSTM(5)(entrada) # 5 unidades (neuronas) de memoria
modelo = Model(inputs=entrada, outputs=lstm_out) # La Api funcional 

print('Información del modelo:')
print()
print('-'*90)
print(modelo.summary()) # Muestra los parámetros internos que genera la red por las puertas lógicas
print('-'*90)
print('Tamaño de entrada: ', modelo.input_shape)
print('Tamaño de salida ', modelo.output_shape)

Información del modelo:

------------------------------------------------------------------------------------------


Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 3, 1)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 5)              │           140 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 140 (560.00 B)

 Trainable params: 140 (560.00 B)

 Non-trainable params: 0 (0.00 B)

None
------------------------------------------------------------------------------------------
Tamaño de entrada:  (None, 3, 1)
Tamaño de salida  (None, 5)


## Demo básica con dos features

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM

# Preparación de los datos - 3 pasos de tiempo, 1 característica
datos = np.array([0.5, 0.4, 0.3]).reshape((1, 3, 1))

# Creamos la arquitectura base
entrada = Input(shape=(3,2)) # Cada paso de tiempo 2 variables (ej: temperatura y humedad)
lstm_out = LSTM(5)(entrada) 
modelo = Model(inputs=entrada, outputs=lstm_out)

print('Información del modelo:')
print()
print('-'*90)
print(modelo.summary())
print('-'*105)
print('Tamaño de entrada: ', modelo.input_shape)
print('Tamaño de salida ', modelo.output_shape)

Información del modelo:

------------------------------------------------------------------------------------------


Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 3, 2)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 5)              │           160 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 160 (640.00 B)

 Trainable params: 160 (640.00 B)

 Non-trainable params: 0 (0.00 B)

None
---------------------------------------------------------------------------------------------------------
Tamaño de entrada:  (None, 3, 2)
Tamaño de salida  (None, 5)


## Demo básica con predicción 



In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# Preparación de los datos - 3 pasos de tiempo, 1 característica
datos = np.array([0.5, 0.4, 0.3]).reshape((3, 1))

# Creamos la arquitectura base
entrada = Input(shape=(3,1))    
lstm_out = LSTM(5)(entrada) 
modelo = Model(inputs=entrada, outputs=lstm_out)

prediccion = modelo.predict(datos, verbose=0) # la red procesa los datos y genera el estado oculto final

print('Información del modelo:')
print('-'*90)
print(modelo.summary())

print('-'*105)
print('Tamaño de entrada: ', modelo.input_shape)
print('Tamaño de salida ', modelo.output_shape)

print()
print('-'*105)
print('Predicción (h_t): ', prediccion)
print('Tamaño predicción: ', prediccion.shape)



Información del modelo:
------------------------------------------------------------------------------------------


Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)      │ (None, 3, 1)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 5)              │           140 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 140 (560.00 B)

 Trainable params: 140 (560.00 B)

 Non-trainable params: 0 (0.00 B)

None
---------------------------------------------------------------------------------------------------------
Tamaño de entrada:  (None, 3, 1)
Tamaño de salida  (None, 5)

---------------------------------------------------------------------------------------------------------
Predicción (h_t):  [[ 0.07100406  0.00103479 -0.03910837 -0.01732945  0.03785019]
 [ 0.05487323  0.00081337 -0.03131501 -0.01416328  0.03130076]
 [ 0.03963583  0.00059927 -0.02347062 -0.01084364  0.02423351]]
Tamaño predicción:  (3, 5)


## Demo básica con return_sequences

In [4]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# Preparación de los datos - 3 pasos de tiempo, 1 característica
datos = np.array([0.5, 0.4, 0.3]).reshape((3, 1))

# Creamos la arquitectura base
entrada = Input(shape=(3,1))    
lstm_out = LSTM(5,
                return_sequences=True)(entrada) # en lugar del resumen final nos da una salida de cada paso de tiempo
modelo = Model(inputs=entrada, outputs=lstm_out)

prediccion = modelo.predict(datos, verbose=0)

print('Información del modelo:')
print('-'*90)
print(modelo.summary())

print('-'*105)
print('Tamaño de entrada: ', modelo.input_shape)
print('Tamaño de salida ', modelo.output_shape)

print()
print('-'*105)
print('Predicción (h_t): ', prediccion)
print('Tamaño predicción: ', prediccion.shape)


Información del modelo:
------------------------------------------------------------------------------------------


Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)      │ (None, 3, 1)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 3, 5)           │           140 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 140 (560.00 B)

 Trainable params: 140 (560.00 B)

 Non-trainable params: 0 (0.00 B)

None
---------------------------------------------------------------------------------------------------------
Tamaño de entrada:  (None, 3, 1)
Tamaño de salida  (None, 3, 5)

---------------------------------------------------------------------------------------------------------
Predicción (h_t):  [[[-0.02365923 -0.00087875  0.03295055 -0.0565184  -0.05210155]]

 [[-0.0189947  -0.00069579  0.02593526 -0.0461386  -0.04051544]]

 [[-0.01427855 -0.00051644  0.01912449 -0.03520462 -0.02948198]]]
Tamaño predicción:  (3, 1, 5)


## Demo básica con return_state

In [5]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# Preparación de los datos - 3 pasos de tiempo, 1 característica
datos = np.array([0.5, 0.4, 0.3]).reshape((3, 1))

# Creamos la arquitectura base
entrada = Input(shape=(3,1))    
lstm_out, h_t, c_t = LSTM(5,
                return_state=True)(entrada) # "Abrimos" la celda para ver tanto la memoria a corto plazo (H) como la de largo plazo (C)
modelo = Model(inputs=entrada, outputs=[lstm_out, h_t, c_t])

prediccion, h, c = modelo.predict(datos, verbose=0)

print('Información del modelo:')
print('-'*90)
print(modelo.summary())

print('-'*105)
print('Tamaño de entrada: ', modelo.input_shape)
print('Tamaño de salida ', modelo.output_shape)

print()
print('-'*105)
print('Predicción (lstm_out): ', prediccion)
print('Tamaño predicción "lstm_out": ', prediccion.shape)

print()
print('-'*105)
print('Predicción (h_t): ', h)
print('Tamaño predicción: ', prediccion.shape)

print()
print('-'*105)
print('Predicción (c_t): ', c)
print('Tamaño predicción "c_t": ', prediccion.shape)


Información del modelo:
------------------------------------------------------------------------------------------


Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_4 (InputLayer)      │ (None, 3, 1)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ [(None, 5), (None, 5), │           140 │
│                                 │ (None, 5)]             │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 140 (560.00 B)

 Trainable params: 140 (560.00 B)

 Non-trainable params: 0 (0.00 B)

None
---------------------------------------------------------------------------------------------------------
Tamaño de entrada:  (None, 3, 1)
Tamaño de salida  [(None, 5), (None, 5), (None, 5)]

---------------------------------------------------------------------------------------------------------
Predicción (lstm_out):  [[ 0.0416259  -0.01026164  0.05192273 -0.00708905  0.010352  ]
 [ 0.03405851 -0.00829373  0.04281355 -0.00580396  0.00839013]
 [ 0.0260875  -0.00627796  0.03303349 -0.00445333  0.00637139]]
Tamaño predicción "lstm_out":  (3, 5)

---------------------------------------------------------------------------------------------------------
Predicción (h_t):  [[ 0.0416259  -0.01026164  0.05192273 -0.00708905  0.010352  ]
 [ 0.03405851 -0.00829373  0.04281355 -0.00580396  0.00839013]
 [ 0.0260875  -0.00627796  0.03303349 -0.00445333  0.00637139]]
Tamaño predicción:  (3, 5)

-----------------------------------------------------------------------------------------------------

## Demo básica: combinación return_sequences-return_state


In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# Preparación de los datos - 3 pasos de tiempo, 1 característica
datos = np.array([0.5, 0.4, 0.3]).reshape((3, 1))

# Creamos la arquitectura base
entrada = Input(shape=(3,1))    
lstm_out, h, c = LSTM(5,
                        return_sequences=True,
                        return_state=True)(entrada)
modelo = Model(inputs=entrada, outputs=[lstm_out, h, c])

prediccion, h, c = modelo.predict(datos, verbose=0)

print('Información del modelo:')
print('-'*90)
print(modelo.summary())

print('-'*105)
print('Tamaño de entrada: ', modelo.input_shape)
print('Tamaño de salida ', modelo.output_shape)

print()
print('-'*105)
print('Predicción (lstm_out): ', prediccion)
print('Tamaño predicción "lstm_out": ', prediccion.shape)

print()
print('-'*105)
print('Predicción (h_t): ', h)
print('Tamaño predicción: ', prediccion.shape)

print()
print('-'*105)
print('Predicción (c_t): ', c)
print('Tamaño predicción "c_t": ', prediccion.shape)




Información del modelo:
------------------------------------------------------------------------------------------


Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_5 (InputLayer)      │ (None, 3, 1)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ [(None, 3, 5), (None,  │           140 │
│                                 │ 5), (None, 5)]         │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 140 (560.00 B)

 Trainable params: 140 (560.00 B)

 Non-trainable params: 0 (0.00 B)

None
---------------------------------------------------------------------------------------------------------
Tamaño de entrada:  (None, 3, 1)
Tamaño de salida  [(None, 3, 5), (None, 5), (None, 5)]

---------------------------------------------------------------------------------------------------------
Predicción (lstm_out):  [[[-0.04126257 -0.05115196  0.02441918 -0.04551592  0.00806825]]

 [[-0.03417749 -0.04143066  0.01901788 -0.03649041  0.00642557]]

 [[-0.02649883 -0.03136873  0.0138726  -0.02738262  0.00479727]]]
Tamaño predicción "lstm_out":  (3, 1, 5)

---------------------------------------------------------------------------------------------------------
Predicción (h_t):  [[-0.04126257 -0.05115196  0.02441918 -0.04551592  0.00806825]
 [-0.03417749 -0.04143066  0.01901788 -0.03649041  0.00642557]
 [-0.02649883 -0.03136873  0.0138726  -0.02738262  0.00479727]]
Tamaño predicción:  (3, 1, 5)

------------------------------------------------------------------------------------

## Demo básica LSTM + CAPA DENSE con función Linear


In [7]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense

# Preparación de los datos - 3 pasos de tiempo, 1 característica
datos = np.array([0.5, 0.4, 0.3]).reshape((3, 1))

# Creamos la arquitectura base
entrada = Input(shape=(3,1))    
lstm_out = LSTM(5)(entrada) 
modelo = Model(inputs=entrada, outputs=lstm_out)

prediccion = modelo.predict(datos, verbose=0)

# Agregar capa de salida Dense
salida = Dense(1)(lstm_out)  # Activación Linear: predice valores numéricos 

print()
print('Información del modelo:')
print()
print('-'*90)
print(modelo.summary())

print()
print('-'*105)
print('Tamaño de entrada: ', modelo.input_shape)
print('Tamaño de salida ', modelo.output_shape)

print()
print('-'*105)
print('Predicción (Regresión): ', prediccion)
print('Tamaño predicción: ', prediccion.shape)


Información del modelo:

------------------------------------------------------------------------------------------


Model: "functional_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_6 (InputLayer)      │ (None, 3, 1)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ (None, 5)              │           140 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 140 (560.00 B)

 Trainable params: 140 (560.00 B)

 Non-trainable params: 0 (0.00 B)

None

---------------------------------------------------------------------------------------------------------
Tamaño de entrada:  (None, 3, 1)
Tamaño de salida  (None, 5)

---------------------------------------------------------------------------------------------------------
Predicción (Regresión):  [[ 0.04407736 -0.03875291  0.03152134 -0.05176667  0.02791404]
 [ 0.035821   -0.03117793  0.0242087  -0.04241772  0.02151401]
 [ 0.02723778 -0.02348118  0.01740441 -0.03251639  0.01552567]]
Tamaño predicción:  (3, 5)


## Demo básica LSTM + CAPA DENSE. Con función Sigmoidal

In [8]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense

# Preparación de los datos - 3 pasos de tiempo, 1 característica
datos = np.array([0.5, 0.4, 0.3]).reshape((3, 1))

# Creamos la arquitectura base
entrada = Input(shape=(3,1))    
lstm_out = LSTM(5)(entrada) 
modelo = Model(inputs=entrada, outputs=lstm_out)

prediccion = modelo.predict(datos, verbose=0)

# Agregar capa de salida Dense
salida = Dense(1, activation='sigmoid')(lstm_out) # Traduce la memoria a una probabilidad entre 0 y 1

print()
print('Información del modelo:')
print()
print('-'*90)
print(modelo.summary())

print()
print('-'*105)
print('Tamaño de entrada: ', modelo.input_shape)
print('Tamaño de salida ', modelo.output_shape)

print()
print('-'*105)
print('Predicción (clasificación binaria): ', prediccion)
print('Tamaño predicción: ', prediccion.shape)



Información del modelo:

------------------------------------------------------------------------------------------


Model: "functional_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_7 (InputLayer)      │ (None, 3, 1)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ (None, 5)              │           140 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 140 (560.00 B)

 Trainable params: 140 (560.00 B)

 Non-trainable params: 0 (0.00 B)

None

---------------------------------------------------------------------------------------------------------
Tamaño de entrada:  (None, 3, 1)
Tamaño de salida  (None, 5)

---------------------------------------------------------------------------------------------------------
Predicción (clasificación binaria):  [[-0.0332453   0.03526884  0.03590459  0.05298553  0.05136788]
 [-0.02630179  0.02937414  0.02907161  0.04395445  0.04090257]
 [-0.01949576  0.02290171  0.02203981  0.03411105  0.03049156]]
Tamaño predicción:  (3, 5)


## Demo básica LSTM + CAPA DENSE. Con función Softmax

In [9]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense

# Preparación de los datos - 3 pasos de tiempo, 1 característica
datos = np.array([0.5, 0.4, 0.3]).reshape((3, 1))

# Creamos la arquitectura base
entrada = Input(shape=(3,1))    
lstm_out = LSTM(5)(entrada) 
modelo = Model(inputs=entrada, outputs=lstm_out)

prediccion = modelo.predict(datos, verbose=0)

# Agregar capa de salida Dense
salida = Dense(1, activation='softmax')(lstm_out)  # Regresión multiclase: elige la categoriía más probable entre varias opciones

print()
print('Información del modelo:')
print()
print('-'*90)
print(modelo.summary())

print()
print('-'*105)
print('Tamaño de entrada: ', modelo.input_shape)
print('Tamaño de salida ', modelo.output_shape)

print()
print('-'*105)
print('Predicción (clasificación multiclase): ', prediccion)
print('Tamaño predicción: ', prediccion.shape)



Información del modelo:

------------------------------------------------------------------------------------------


Model: "functional_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_8 (InputLayer)      │ (None, 3, 1)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_8 (LSTM)                   │ (None, 5)              │           140 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 140 (560.00 B)

 Trainable params: 140 (560.00 B)

 Non-trainable params: 0 (0.00 B)

None

---------------------------------------------------------------------------------------------------------
Tamaño de entrada:  (None, 3, 1)
Tamaño de salida  (None, 5)

---------------------------------------------------------------------------------------------------------
Predicción (clasificación multiclase):  [[ 0.00078528  0.02953133 -0.04016993  0.0439566  -0.06026776]
 [ 0.00062815  0.02361781 -0.03156774  0.0359872  -0.04941656]
 [ 0.00047106  0.01768716 -0.02323081  0.02758173 -0.0378882 ]]
Tamaño predicción:  (3, 5)
