# Boletín de Ejercicios 1: NumPy

## Fundamentos del Cálculo Numérico en Python

**Objetivo:** Dominar las operaciones fundamentales con NumPy para el análisis de datos numéricos.

**Instrucciones:**
- Resuelve cada ejercicio en la celda de código correspondiente
- Ejecuta las celdas para verificar tus resultados
- Los ejercicios están ordenados de menor a mayor dificultad
- 🟢 = Básico | 🟡 = Intermedio | 🔴 = Avanzado

---

In [4]:
# Importar NumPy
import numpy as np

lima = '\33[38;5;46m'
reset = '\033[0m'

# Verificar versión
print(f"\n{lima}NumPy versión: {np.__version__}{reset}")


NumPy versión: 2.2.6


## 🟢 Ejercicio 1: Tu Primer Array

Crea un array de NumPy con los siguientes datos:
- Temperaturas diarias de una semana: `[22, 24, 19, 25, 23, 21, 20]`
- Imprime el array
- Imprime el tipo de dato del array
- Imprime la forma (shape) del array

In [ ]:
# Título: Mi primer Array
# Autor: Ivana Sánchez Pérez

import numpy as np

# colores
rojo = '\033[91m'
verde = '\033[92m'
azul = '\033[94m'
magenta = '\033[95m'
amarillo = '\033[93m'
rosa = '\033[38;5;200m'
turquesa = '\033[38;5;44m'
azul_marino = '\33[38;5;67m'
lima = '\33[38;5;46m'
reset = '\033[0m'

# Lista de temperaturas
temperaturas_lista = [22, 24, 19, 25, 23, 21, 20]
print(f"\n{azul}Lista Python:{reset}", temperaturas_lista)

# Convertimos en array de NumPy
temperaturas = np.array(temperaturas_lista)
print(f"{rosa}Array NumPy:{reset}", temperaturas)
print(f"{lima}Tipo:{reset}", type(temperaturas))
print(f"{turquesa} .shape:{reset} {temperaturas.shape}")



Lista Python: [22, 24, 19, 25, 23, 21, 20]
Array NumPy: [22 24 19 25 23 21 20]
Tipo: <class 'numpy.ndarray'>
 .shape: (7,)


## 🟢 Ejercicio 2: Operaciones Básicas

Usando el array de temperaturas del ejercicio anterior:
1. Calcula la temperatura media de la semana
2. Encuentra la temperatura máxima y mínima
3. Calcula la desviación estándar
4. ¿Cuántos días tuvieron temperatura superior a 22°C?

In [11]:
# Título: Operaciones Básicas
# Autor: Ivana Sánchez Pérez

import numpy as np

# colores
rojo = '\033[91m'
verde = '\033[92m'
azul = '\033[94m'
magenta = '\033[95m'
amarillo = '\033[93m'
rosa = '\033[38;5;200m'
turquesa = '\033[38;5;44m'
azul_marino = '\33[38;5;67m'
lima = '\33[38;5;46m'
reset = '\033[0m'

temperaturas = np.array(temperaturas_lista)
temperaturas_superiores_22 = np.sum(temperaturas >22)

print(f"\n{azul}La temperatura media de la semana ha sido: {reset} {temperaturas.mean():.2f}")
print(f"{rosa}La temperatura máxima de la semana ha sido:{reset} {temperaturas.max()}")
print(f"{lima}La temperatura mínimo de la semana ha sido:{reset} {temperaturas.min()}")
print(f"{turquesa}La desviación estándar de la semana ha sido: {reset} {temperaturas.std():.2f}")
print(f"{rojo}Los días que superaron los 22ºC fueron:{reset} {temperaturas_superiores_22}")



La temperatura media de la semana ha sido:  22.00
La temperatura máxima de la semana ha sido: 25
La temperatura mínimo de la semana ha sido: 19
La desviación estándar de la semana ha sido:  2.00
Los días que superaron los 22ºC fueron: 3


## 🟢 Ejercicio 3: Creación de Arrays con Funciones

Crea los siguientes arrays usando las funciones de NumPy:
1. Un array de 10 ceros
2. Un array de 8 unos
3. Un array con números del 0 al 20 (sin incluir el 20)
4. Un array con números del 10 al 100 de 10 en 10
5. Un array de 5 elementos espaciados uniformemente entre 0 y 1

In [2]:
# Título: Creación de Arrays con Funciones
# Autor: Ivana Sánchez Pérez

import numpy as np

# colores
rojo = '\033[91m'
verde = '\033[92m'
azul = '\033[94m'
magenta = '\033[95m'
amarillo = '\033[93m'
rosa = '\033[38;5;200m'
turquesa = '\033[38;5;44m'
azul_marino = '\33[38;5;67m'
lima = '\33[38;5;46m'
reset = '\033[0m'

# Un array de 10 ceros 
array_ceros = np.zeros(10)
print(f"\n{azul}1. Array de 10 ceros:{reset}")
print(f"{magenta}{array_ceros}{reset}")

# Un array de 8 unos
array_unos = np.ones(8)
print(f"\n{azul}2. Array de 8 unos:{reset}")
print(f"{magenta}{array_unos}{reset}")

# Un array con números del 0 al 20 (sin incluir el 20) 
array_0_a_19 = np.arange(0, 20, 1)
print(f"\n{azul}3. Array del 0 al 19:{reset}")
print(f"{magenta}{array_0_a_19}{reset}")

# Un array con números del 10 al 100 de 10 en 10 
array_10_a_100 = np.arange(10, 101, 10)
print(f"\n{azul}4. Array del 10 al 100 (de 10 en 10):{reset}")
print(f"{magenta}{array_10_a_100}{reset}")

# Un array de 5 elementos espaciados uniformemente entre 0 y 1
array_linspace = np.linspace(0, 1, 5)
print(f"\n{azul}5. Array de 5 elementos uniformemente espaciados entre 0 y 1:{reset}")
print(f"{magenta}{array_linspace}{reset}")



1. Array de 10 ceros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

2. Array de 8 unos:
[1. 1. 1. 1. 1. 1. 1. 1.]

3. Array del 0 al 19:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

4. Array del 10 al 100 (de 10 en 10):
[ 10  20  30  40  50  60  70  80  90 100]

5. Array de 5 elementos uniformemente espaciados entre 0 y 1:
[0.   0.25 0.5  0.75 1.  ]


## 🟡 Ejercicio 4: Indexación y Slicing

Dado el array: `ventas = np.array([120, 135, 142, 158, 161, 149, 155, 168, 172, 180])`

1. Obtén las ventas de los primeros 3 días
2. Obtén las ventas de los últimos 4 días
3. Obtén las ventas de los días pares (índices 0, 2, 4, ...)
4. Invierte el orden del array
5. Obtén las ventas mayores de 150

In [20]:
# Título: Indexación y Slicing
# Autor: Ivana Sánchez Pérez

import numpy as np

# colores
rojo = '\033[91m'
verde = '\033[92m'
azul = '\033[94m'
magenta = '\033[95m'
amarillo = '\033[93m'
rosa = '\033[38;5;200m'
turquesa = '\033[38;5;44m'
azul_marino = '\33[38;5;67m'
lima = '\33[38;5;46m'
reset = '\033[0m'

ventas = np.array([120, 135, 142, 158, 161, 149, 155, 168, 172, 180])

print(f"{azul}\nVenta de los tres primeros días:{reset}{turquesa} {ventas[0:3]}{reset}")
print(f"{azul}Venta de los cuatro últimos días:{reset}{turquesa} {ventas[-4]}{reset}")
print(f"{azul}Venta de los días pares:{reset}{turquesa} {ventas[::2]}{reset}")
print(f"{azul}Inversión del Array:{reset}{turquesa} {ventas[::-1]}{reset}")
print(f"{azul}Ventas mayores de 150:{reset}{turquesa} {ventas[ventas>150]}{reset}")


Venta de los tres primeros días: [120 135 142]
Venta de los cuatro últimos días: 155
Venta de los días pares: [120 142 161 155 172]
Inversión del Array: [180 172 168 155 149 161 158 142 135 120]
Ventas mayores de 150: [158 161 155 168 172 180]


## 🟡 Ejercicio 5: Arrays Multidimensionales

Crea una matriz 4x3 (4 filas, 3 columnas) que represente las ventas de 3 productos durante 4 semanas:

```
Semana  | Producto A | Producto B | Producto C
--------|------------|------------|------------
   1    |     45     |     62     |     38
   2    |     52     |     58     |     41
   3    |     48     |     67     |     45
   4    |     55     |     71     |     43
```

Luego:
1. Imprime las dimensiones de la matriz
2. Calcula las ventas totales por producto (suma de cada columna)
3. Calcula las ventas totales por semana (suma de cada fila)
4. Encuentra el producto con mayores ventas totales

In [37]:
# Título: Arrays Multidimensionales
# Autor: Ivana Sánchez Pérez

import numpy as np

# colores
rojo = '\033[91m'
verde = '\033[92m'
azul = '\033[94m'
magenta = '\033[95m'
amarillo = '\033[93m'
rosa = '\033[38;5;200m'
turquesa = '\033[38;5;44m'
azul_marino = '\33[38;5;67m'
lima = '\33[38;5;46m'
reset = '\033[0m'

ventas = np.array([
    [45, 62, 38],  
    [52, 58, 41],  
    [48, 67, 45],  
    [55, 71, 43]   
])

print(f"\n{azul}{ventas}{reset}")
print(f"\n{turquesa} Las ventas totales por columnas son: {reset}{lima}{ventas.sum(axis=0)}{reset}")
print(f"{turquesa} Las ventas totales por filas son: {reset}{lima}{ventas.sum(axis=1)}{reset}")

# Encontrar producto con mayores ventas
ventas_totales = ventas.sum(axis=0)
productos = ["A", "B", "C"]
indice_max = np.argmax(ventas_totales)
producto_max = productos[indice_max]
total_max = ventas_totales[indice_max]


print(f"{turquesa} El producto que tiene las mayores ventas es:{reset}{lima} El producto {producto_max} con {total_max} unidades{reset}")





[[45 62 38]
 [52 58 41]
 [48 67 45]
 [55 71 43]]

 Las ventas totales por columnas son: [200 258 167]
 Las ventas totales por filas son: [145 151 160 169]
 El producto que tiene las mayores ventas es: El producto B con 258 unidades


## 🟡 Ejercicio 6: Operaciones Vectorizadas

Tienes datos de un experimento científico:
- Tiempo (segundos): `[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`
- Velocidad (m/s): `[0, 2.3, 4.1, 5.8, 7.2, 8.9, 10.1, 11.5, 12.8, 14.0, 15.2]`

Calcula:
1. **La aceleración promedio** 
   - Ayuda: aceleración = (velocidad_final - velocidad_inicial) / (tiempo_final - tiempo_inicial)
   - Usa indexación: `velocidad[-1]` para el último elemento, `velocidad[0]` para el primero

2. **Convierte velocidades a km/h**
   - Ayuda: km/h = m/s × 3.6
   - Usa operación vectorizada: `array * 3.6`

3. **Distancia aproximada recorrida**
   - Ayuda: Suma de velocidad × tiempo para cada intervalo
   - Calcula los cambios de tiempo entre segundos consecutivos restando: `tiempo[1:] - tiempo[:-1]`
   - Calcula velocidad promedio entre puntos: `(v1 + v2) / 2`
   - Suma todo: `np.sum(velocidades * tiempos)`


In [ ]:
# Título: Operaciones Vectorizadas
# Autor: Ivana Sánchez Pérez

import numpy as np

# colores
rojo = '\033[91m'
verde = '\033[92m'
azul = '\033[94m'
magenta = '\033[95m'
amarillo = '\033[93m'
rosa = '\033[38;5;200m'
turquesa = '\033[38;5;44m'
azul_marino = '\33[38;5;67m'
lima = '\33[38;5;46m'
reset = '\033[0m'

tiempo = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
velocidad = np.array([0, 2.3, 4.1, 5.8, 7.2, 8.9, 10.1, 11.5, 12.8, 14.0, 15.2])

# 1. Aceleración promedio
aceleracion_promedio = (velocidad[-1] - velocidad[0]) / (tiempo[-1] - tiempo[0])
print(f"\n{azul}1-Aceleración promedio:{reset} {magenta}{aceleracion_promedio}{reset}")

# 2. Convertir velocidad a km/h
velocidad_kmh = velocidad * 3.6
print(f"{azul}2-Velocidades (km/h):{reset} {magenta}{velocidad_kmh}{reset}")

# 3. Distancia aproximada
dt = tiempo[1:] - tiempo[:-1]

# Velocidad promedio entre puntos
v_prom = (velocidad[1:] + velocidad[:-1]) / 2

# Distancia total
distancia = np.sum(v_prom * dt)
print(f"{azul}3-Distancia recorrida aproximada:{reset} {magenta}{distancia}{reset}")


1-Aceleración promedio: 1.52
2-Velocidades (km/h): [ 0.    8.28 14.76 20.88 25.92 32.04 36.36 41.4  46.08 50.4  54.72]
3-Distancia recorrida aproximada: 84.3


## 🟡 Ejercicio 7: Lógica Condicional Vectorizada con np.where()

Tienes un array de calificaciones de estudiantes:
- `calificaciones = np.array([45, 72, 88, 65, 92, 58, 78, 95, 52, 81])`

Usa `np.where()` para:
1. Crear un array que clasifique cada calificación como "APROBADO" (>= 60) o "SUSPENDIDO" (< 60)
2. Reemplazar todas las calificaciones menores a 60 con 60 (ajuste mínimo)
3. Crear un array con bonificación: si la calificación es >= 80, suma 5 puntos; si no, mantén la original
4. Contar cuántos estudiantes están en cada categoría (0-50, 50-70, 70-90, 90-100)

In [5]:
# Título: Lógica Condicional Vectorizada con np.Where()
# Autor: Ivana Sánchez Pérez

import numpy as np

# colores
rojo = '\033[91m'
verde = '\033[92m'
azul = '\033[94m'
magenta = '\033[95m'
amarillo = '\033[93m'
rosa = '\033[38;5;200m'
turquesa = '\033[38;5;44m'
azul_marino = '\33[38;5;67m'
lima = '\33[38;5;46m'
reset = '\033[0m'

calificaciones = np.array([45, 72, 88, 65, 92, 58, 78, 95, 52, 81])

print(f"{azul}Calificaciones originales: {reset}{magenta}{calificaciones}{reset}")

clasificacion = np.where(calificaciones >=60, "Aprobado", "Suspendido")
print(f"\n{turquesa}1- Clasificación: {reset}\n{lima}{clasificacion}{reset}")

ajuste_minimo = np.where(calificaciones < 60, 60, calificaciones)
print(f"\n{turquesa}2- Clasificaciones con ajuste mínimo: {reset}\n{lima}{ajuste_minimo}{reset}")

bonificacion = np.where(calificaciones >= 80, calificaciones + 5, calificaciones)
print(f"\n{turquesa}3- Clasificaciones con bonificación: {reset}\n{lima}{bonificacion}{reset}")

# Definición de los límites de las categorías
cat_0_50 = (calificaciones >= 0) & (calificaciones <= 50)
cat_50_70 = (calificaciones > 50) & (calificaciones <= 70)
cat_70_90 = (calificaciones > 70) & (calificaciones <= 90)
cat_90_100 = (calificaciones > 90) & (calificaciones <= 100)

# Conteo de estudiantes en cada categoría
count_0_50 = np.count_nonzero(cat_0_50)
count_50_70 = np.count_nonzero(cat_50_70)
count_70_90 = np.count_nonzero(cat_70_90)
count_90_100 = np.count_nonzero(cat_90_100)

print(f"{turquesa}4- Conteo de estudiantes por categoría:{reset}")
print(f"   {lima}0-50: {count_0_50} estudiantes (Calificaciones: {calificaciones[cat_0_50]})")
print(f"   50-70: {count_50_70} estudiantes (Calificaciones: {calificaciones[cat_50_70]})")
print(f"   70-90: {count_70_90} estudiantes (Calificaciones: {calificaciones[cat_70_90]})")
print(f"   90-100: {count_90_100} estudiantes (Calificaciones: {calificaciones[cat_90_100]}){reset}")


Calificaciones originales: [45 72 88 65 92 58 78 95 52 81]

1- Clasificación: 
['Suspendido' 'Aprobado' 'Aprobado' 'Aprobado' 'Aprobado' 'Suspendido'
 'Aprobado' 'Aprobado' 'Suspendido' 'Aprobado']

2- Clasificaciones con ajuste mínimo: 
[60 72 88 65 92 60 78 95 60 81]

3- Clasificaciones con bonificación: 
[ 45  72  93  65  97  58  78 100  52  86]
4- Conteo de estudiantes por categoría:
   0-50: 1 estudiantes (Calificaciones: [45])
   50-70: 3 estudiantes (Calificaciones: [65 58 52])
   70-90: 4 estudiantes (Calificaciones: [72 88 78 81])
   90-100: 2 estudiantes (Calificaciones: [92 95])


## 🔴 Ejercicio 8: Análisis de Datos Aleatorios

Genera datos simulados de rendimiento de estudiantes:
1. Crea una matriz 50x5 con notas aleatorias entre 0 y 10 (50 estudiantes, 5 exámenes)
   - Usa `np.random.uniform(0, 10, (50, 5))`
2. Calcula la nota media de cada estudiante
3. Calcula la nota media de cada examen
4. ¿Cuántos estudiantes tienen una media superior a 7?
5. Encuentra el estudiante con la mejor media (índice)
6. Encuentra el examen más difícil (el que tiene menor media)

In [17]:
# Título: Análisis de datos aleatorios
# Autor: Ivana Sánchez Pérez

import numpy as np

# colores
rojo = '\033[91m'
verde = '\033[92m'
azul = '\033[94m'
magenta = '\033[95m'
amarillo = '\033[93m'
rosa = '\033[38;5;200m'
turquesa = '\033[38;5;44m'
azul_marino = '\33[38;5;67m'
lima = '\33[38;5;46m'
reset = '\033[0m'

# Establecer semilla para reproducibilidad
np.random.seed(42)

notas = np.random.uniform(0, 10, (50, 5))
print(f"{azul}\n                 Matíz Notas Estudiantes{reset}\n{lima}{notas[:3]}")
print("...")
print(f"{notas[-3:]}{reset}")

media_estudiantes = np.mean(notas, axis=1)
print(f"\n{azul}                Media de cada estudiante{reset}\n{lima}{media_estudiantes}{reset}")

media_examenes = np.mean(notas, axis=0)
print(f"{azul}\nMedia de cada examen:\n{reset}", media_examenes)

estudiantes_sobresalientes = np.sum(media_estudiantes > 7)
print(f"{azul}\nNúmero de estudiantes con media > 7:{reset}", estudiantes_sobresalientes)

mejor_estudiante = np.argmax(media_estudiantes)
print(f"{azul}\nÍndice del mejor estudiante:{reset}", mejor_estudiante)

examen_mas_dificil = np.argmin(media_examenes)
print(f"{azul}\nÍndice del examen más difícil:{reset}", examen_mas_dificil)



                 Matíz Notas Estudiantes
[[3.74540119 9.50714306 7.31993942 5.98658484 1.5601864 ]
 [1.5599452  0.58083612 8.66176146 6.01115012 7.08072578]
 [0.20584494 9.69909852 8.32442641 2.12339111 1.81824967]]
...
[[7.22452115 2.80772362 0.24315966 6.45472296 1.77110679]
 [9.40458584 9.53928577 9.1486439  3.701587   0.15456617]
 [9.28318563 4.28184148 9.66654819 9.63619977 8.53009455]]

                Media de cada estudiante
[5.62385098 4.77888374 4.43420213 3.47115469 3.73184646 4.27589833
 5.51527628 4.6701375  3.6394081  4.45173223 8.35388744 3.15381444
 4.25290333 5.09450974 4.99760268 4.09731391 4.3836805  6.10354928
 5.85173692 3.15476    4.79666549 3.44200873 5.64438906 6.58720793
 4.71904403 5.24710514 4.07981811 5.7608484  4.5943938  2.95851104
 5.53565173 5.28332865 4.51936626 3.94853831 4.15582763 4.65258089
 5.02902894 5.60781985 5.72573566 7.27847497 4.78556715 1.88008
 5.65807755 5.615993   3.90502887 6.26656621 5.12422593 3.70024684
 6.38973374 8.27957393]

Medi

## 🔴 Ejercicio 9: Normalización de Datos

La normalización es una técnica crucial en machine learning. Normaliza los siguientes datos usando dos métodos:

Datos: `datos = np.array([23, 45, 67, 89, 12, 34, 56, 78, 90, 100])`

**Método 1: Min-Max Scaling (0-1)**
- Fórmula: `(x - min) / (max - min)`
- Los valores deben quedar entre 0 y 1

**Método 2: Estandarización (Z-score)**
- Fórmula: `(x - media) / desviación_estándar`
- Los valores deben tener media 0 y desviación estándar 1

---

**¿Cómo verificar que las normalizaciones son correctas?**

Después de normalizar, debes calcular:

1. **Para Min-Max Scaling:**
   - Media de los datos normalizados: debería estar entre 0 y 1
   - Mínimo de los datos normalizados: debería ser exactamente 0
   - Máximo de los datos normalizados: debería ser exactamente 1

2. **Para Estandarización (Z-score):**
   - Media de los datos normalizados: debería ser aproximadamente 0 (ej: 0.0000001)
   - Desviación estándar: debería ser aproximadamente 1 (ej: 0.9999 o 1.0001)

Imprime estos valores para confirmar que tu normalización fue correcta.

In [15]:
# Título: Normlización de datos
# Autor: Ivana Sánchez Pérez

import numpy as np

# colores
rojo = '\033[91m'
verde = '\033[92m'
azul = '\033[94m'
magenta = '\033[95m'
amarillo = '\033[93m'
rosa = '\033[38;5;200m'
turquesa = '\033[38;5;44m'
azul_marino = '\33[38;5;67m'
lima = '\33[38;5;46m'
reset = '\033[0m'

datos = np.array([23, 45, 67, 89, 12, 34, 56, 78, 90, 100])
print(f"\n{azul}Datos originales:{reset}\n{turquesa}{datos}{reset}")

# Variables de cálculo general 
media_original = np.mean(datos)
std_original = np.std(datos)
min_original = np.min(datos)
max_original = np.max(datos)

denominador = max_original - min_original
datos_minmax = (datos - min_original) / denominador

print(f"\n{azul}Método 1: Min-Max Scaling{reset}")
print(f"{turquesa}Datos Normalizados (Min-Max):{reset}\n{lima}{datos_minmax.round(4)}{reset}")

# Verificación
minmax_media = np.mean(datos_minmax)
minmax_min = np.min(datos_minmax)
minmax_max = np.max(datos_minmax)

print(f"\n{azul}Verificación Min-Max:{reset}")
print(f"{turquesa}* Media de normalizados:{reset}{lima} {minmax_media:.4f} (Debe estar entre 0 y 1){reset}")
print(f"{turquesa}* Mínimo:{reset}{lima} {minmax_min:.4f} (Debe ser 0){reset}")
print(f"{turquesa}* Máximo:{reset}{lima} {minmax_max:.4f} (Debe ser 1){reset}")

datos_zscore = (datos - media_original) / std_original

print(f"{azul}\nMétodo 2: Estandarización Z-score{reset}")
print(f"{turquesa}Datos Estandarizados (Z-score):{reset}\n{lima}{datos_zscore.round(4)}{reset}")

zscore_media = np.mean(datos_zscore)
zscore_std = np.std(datos_zscore)

print(f"{azul}\nVerificación Z-score:{reset}")
print(f"{turquesa}* Media de estandarizados:{reset}{lima} {zscore_media:.10f} (Debe ser ≈ 0){reset}")
print(f"{turquesa}* Desviación estándar:{reset}{lima} {zscore_std:.4f} (Debe ser ≈ 1){reset}")




Datos originales:
[ 23  45  67  89  12  34  56  78  90 100]

Método 1: Min-Max Scaling
Datos Normalizados (Min-Max):
[0.125  0.375  0.625  0.875  0.     0.25   0.5    0.75   0.8864 1.    ]

Verificación Min-Max:
* Media de normalizados: 0.5386 (Debe estar entre 0 y 1)
* Mínimo: 0.0000 (Debe ser 0)
* Máximo: 1.0000 (Debe ser 1)

Método 2: Estandarización Z-score
Datos Estandarizados (Z-score):
[-1.2634 -0.4998  0.2638  1.0274 -1.6452 -0.8816 -0.118   0.6456  1.0621
  1.4092]

Verificación Z-score:
* Media de estandarizados: 0.0000000000 (Debe ser ≈ 0)
* Desviación estándar: 1.0000 (Debe ser ≈ 1)


## 🔴 Ejercicio 10: Análisis de Series Temporales

Tienes datos de temperatura horaria durante 24 horas (simulados):

```python
np.random.seed(42)
horas = np.arange(0, 24)
# Temperatura base con patrón sinusoidal + ruido
temperatura = 20 + 5 * np.sin(2 * np.pi * horas / 24) + np.random.normal(0, 1, 24)
```

Realiza el siguiente análisis:
1. Calcula la temperatura media del día
2. Encuentra la hora más calurosa y la más fría
3. Identifica las horas donde la temperatura estuvo por encima de la media
4. Calcula el rango de temperatura (diferencia entre máxima y mínima)

In [12]:
# Título: Análisis de series temporales
# Autor: Ivana Sánchez Pérez

import numpy as np

# colores
rojo = '\033[91m'
verde = '\033[92m'
azul = '\033[94m'
magenta = '\033[95m'
amarillo = '\033[93m'
rosa = '\033[38;5;200m'
turquesa = '\033[38;5;44m'
azul_marino = '\33[38;5;67m'
lima = '\33[38;5;46m'
reset = '\033[0m'

np.random.seed(42)
horas = np.arange(0, 24)
temperatura = 20 + 5 * np.sin(2 * np.pi * horas / 24) + np.random.normal(0, 1, 24)

print(f"{azul}Datos de Tempernatura{reset}")
print(f"\n{lima}Horas:{reset}{turquesa} {horas}{reset}")
print(f"{lima}Temperaturas: {reset}{turquesa}{np.round(temperatura, 2)}{reset}")

media_dia = np.mean(temperatura)

print(f"\n{azul}1- Temperatura media del día:{reset}{turquesa} {media_dia:.2f}°{reset}")

hora_max = np.argmax(temperatura)
temp_max = np.max(temperatura)

hora_min = np.argmin(temperatura)
temp_min = np.min(temperatura)

print(f"\n{azul}2- Horas extremas:{reset}")
print(f"{turquesa}   Hora más calurosa: {hora_max}:00 h ({temp_max:.2f}°){reset}")
print(f"{turquesa}   Hora más fría: {hora_min}:00 h ({temp_min:.2f}°){reset}")

horas_por_encima = horas[temperatura > media_dia]
temperaturas_por_encima = temperatura[temperatura > media_dia]

print(f"\n{azul}3- Horas con temperatura por encima de la media:{reset}")
print(f"{turquesa}   Horas: {horas_por_encima}{reset}")
print(f"{turquesa}   Temperaturas: {np.round(temperaturas_por_encima, 2)}{reset}")

rango_temperatura = temp_max - temp_min

print(f"\n{azul}4- Rango de temperatura (Máx - Mín):{reset}{turquesa} {rango_temperatura:.2f}°{reset}")

Datos de Tempernatura

Horas: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Temperaturas: [20.5  21.16 23.15 25.06 24.1  24.6  26.58 25.6  23.86 24.08 22.04 20.83
 20.24 16.79 15.78 15.9  14.66 15.48 14.09 13.76 17.14 16.24 17.57 17.28]

1- Temperatura media del día: 19.85°

2- Horas extremas:
   Hora más calurosa: 6:00 h (26.58°)
   Hora más fría: 19:00 h (13.76°)

3- Horas con temperatura por encima de la media:
   Horas: [ 0  1  2  3  4  5  6  7  8  9 10 11 12]
   Temperaturas: [20.5  21.16 23.15 25.06 24.1  24.6  26.58 25.6  23.86 24.08 22.04 20.83
 20.24]

4- Rango de temperatura (Máx - Mín): 12.82°


## 🔴 Ejercicio BONUS: Álgebra Lineal Aplicada

Una empresa tiene 3 tiendas y vende 4 productos. Tienes dos matrices:

**Matriz de Inventario** (tiendas × productos):
```
         P1   P2   P3   P4
Tienda1  50   30   20   40
Tienda2  60   25   35   45
Tienda3  45   40   30   50
```

**Vector de Precios** (precio por producto):
```
P1: 10€
P2: 25€
P3: 15€
P4: 30€
```

Usando multiplicación de matrices:
1. Calcula el valor total del inventario de cada tienda
2. ¿Qué tienda tiene el inventario más valioso?
3. ¿Cuál es el valor total del inventario de toda la empresa?

**Pista:** Usa `np.dot()` o el operador `@` para multiplicación de matrices.

In [7]:
# Título: Álgebra linel avanzada
# Autor: Ivana Sánchez Pérez

import numpy as np

# colores
rojo = '\033[91m'
verde = '\033[92m'
azul = '\033[94m'
magenta = '\033[95m'
amarillo = '\033[93m'
rosa = '\033[38;5;200m'
turquesa = '\033[38;5;44m'
azul_marino = '\33[38;5;67m'
lima = '\33[38;5;46m'
reset = '\033[0m'

# Matriz de Inventario 
inventario = np.array([
    [50, 30, 20, 40],  
    [60, 25, 35, 45],  
    [45, 40, 30, 50]   
])

# Vector de Precios
precios = np.array([10, 25, 15, 30]).reshape(-1, 1)

print(f"{azul}Matriz de Inventario:{reset}\n{lima}{inventario}{reset}")
print(f"{azul}\nVector de Precios:\n{lima}{precios}{reset}")


valor_por_tienda = inventario @ precios

print(f"{azul}\n1- Valor Total del Inventario por Tienda:{reset}")
print(f"{turquesa}   Tienda 1: {valor_por_tienda[0, 0]:.2f} €{reset}")
print(f"{turquesa}   Tienda 2: {valor_por_tienda[1, 0]:.2f} €{reset}")
print(f"{turquesa}   Tienda 3: {valor_por_tienda[2, 0]:.2f} €{reset}")
print(f"\n{azul}Vector de Resultados:{reset}")
print(f"{turquesa}{valor_por_tienda}{reset}")

indice_max_valor = np.argmax(valor_por_tienda)
tienda_mas_valiosa = indice_max_valor + 1

print(f"\n{azul}2- Tienda con el inventario más valioso:{reset}")
print(f"{turquesa}   La tienda {tienda_mas_valiosa} tiene el inventario más valioso.{reset}")

valor_total_empresa = np.sum(valor_por_tienda)

print(f"\n{azul}3- Valor Total del Inventario de toda la Empresa:{reset}")
print(f"{turquesa}   Valor Total: {valor_total_empresa:.2f} €{reset}")

Matriz de Inventario:
[[50 30 20 40]
 [60 25 35 45]
 [45 40 30 50]]

Vector de Precios:
[[10]
 [25]
 [15]
 [30]]

1- Valor Total del Inventario por Tienda:
   Tienda 1: 2750.00 €
   Tienda 2: 3100.00 €
   Tienda 3: 3400.00 €

Vector de Resultados:
[[2750]
 [3100]
 [3400]]

2- Tienda con el inventario más valioso:
   La tienda 3 tiene el inventario más valioso.

3- Valor Total del Inventario de toda la Empresa:
   Valor Total: 9250.00 €


---

## ✅ Finalización del Boletín

Se han completado los ejercicios de NumPy. Los temas cubiertos incluyen:
- ✅ Creación y manipulación de arrays
- ✅ Operaciones estadísticas básicas
- ✅ Indexación y slicing avanzado
- ✅ Arrays multidimensionales
- ✅ Vectorización y broadcasting
- ✅ Análisis de datos numéricos
- ✅ Álgebra lineal aplicada

**Siguientes pasos:**
- Practicar con ejercicios propios
- Revisar las soluciones proporcionadas
- Aplicar los conceptos en casos de uso reales